version: "3.8"

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: yarn start
